# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/hfdem/android_gki_kernel_5.15_common
          kernel-dir: msm-5.15
          kernel-branch: android13-5.15-2025-05
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 13
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
